### ISSUE TITLE
Добавить редактор кода

### ISSUE THREAD

**Issue by grigoriy-grisha** [deep-assistant/GPTutor#7]

**Comment by dmitriypereverza** [comment]
а как это примерно должно выглядеть? есть пример?

**Comment by grigoriy-grisha** [comment]
Пока точно даже не знаю, что это может понадобиться.

Но я это вижу так:

В Writebar-е появляется какой-то виджет с оконкой "Код", при нажатии выезжает модалка(BottomSheet) или поле инпута расширяется, и пользователь может писать что-то в модалке и у него просто будет какая-то подсветка хотя бы.
Думаю, вообще редактор это оверхед для такого приложения и он точно долго будет не нужен

<img width="848" alt="Снимок экрана 2023-04-22 в 01 40 16" src="https://user-images.githubusercontent.com/67334706/233744865-652c2f0c-ceb6-4772-bc54-60160bb3241d.png">
